<?php

namespace OffreBundle\Repository;
use AppBundle\Entity\Entreprise;
use AppBundle\Entity\User;
use OffreBundle\Entity\Offre;

/**
 * CandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEntrepriseCandidatures(User $user){
        return $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.offre','o')
            ->where('o.user = :user')
            ->setParameter('user',$user->getId())
            ->getQuery()->getResult();
    }

    public function getCountCandidatures(User $user) : int {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c) as count')
            ->leftJoin('c.offre','o')
            ->where('o.user = :user')
            ->setParameter('user',$user->getId())
            ->getQuery()->getSingleResult()['count'];
    }
}
