<?php

namespace OffreBundle\Repository;
use AppBundle\Entity\Entreprise;
use AppBundle\Entity\User;
use OffreBundle\Entity\Offre;

/**
 * CandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEntrepriseCandidatures(User $user){
        return $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.offre','o')
            ->where('o.user = :user')
            ->setParameter('user',$user->getId())
            ->getQuery()->getResult();
    }

    public function getCountCandidatures(User $user) : int {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c) as count')
            ->leftJoin('c.offre','o')
            ->where('o.user = :user')
            ->setParameter('user',$user->getId())
            ->getQuery()->getSingleResult()['count'];
    }

    public function getAgendaEntreprise(User $user, $limit = null){

        // Définition requête
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.offre', 'o')
            ->where('o.user = :user')
            ->andWhere('c.dateMeeting IS NOT NULL')
            ->andWhere('c.dateMeeting > :date')
            ->setParameter('user', $user)
            ->setParameter('date', new \DateTime())
            ->orderBy('c.dateMeeting','ASC');

        // Limitation résultat
        if (!is_null($limit)) {
            $query->setMaxResults($limit);
        }

        // Retour du résultat
        return $query->getQuery()->getResult();
    }
}
