<?php

namespace AppBundle\Repository;

/**
 * ForumUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumUserRepository extends \Doctrine\ORM\EntityRepository
{
}
