offre:
    resource: "@OffreBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /offres

candidature:
    resource: "@OffreBundle/Controller/CandidatureController.php"
    type:     annotation
    prefix:   /candidatures

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile


easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
#assets:install --symlink
yosimitso_working_forum:
  resource: "@YosimitsoWorkingForumBundle/Resources/config/routing.yml"
  prefix:   /forum